\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Introduction to data},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Introduction to data}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

\subsection{Getting started}\label{getting-started}

The Behavioral Risk Factor Surveillance System (BRFSS) is an annual
telephone survey of 350,000 people in the United States. As its name
implies, the BRFSS is designed to identify risk factors in the adult
population and report emerging health trends. For example, respondents
are asked about their diet and weekly physical activity, their HIV/AIDS
status, possible tobacco use, and even their level of healthcare
coverage. The BRFSS Web site (\url{http://www.cdc.gov/brfss}) contains a
complete description of the survey, including the research questions
that motivate the study and many interesting results derived from the
data.

We will focus on a random sample of 20,000 people from the BRFSS survey
conducted in 2000. While there are over 200 variables in this data set,
we will work with a small subset.

We begin by loading the data set of 20,000 observations into the R
workspace. After launching RStudio, enter the following command.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{source}\NormalTok{(}\StringTok{"more/cdc.R"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The data set \texttt{cdc} that shows up in your workspace is a
\emph{data matrix}, with each row representing a \emph{case} and each
column representing a \emph{variable}. R calls this data format a
\emph{data frame}, which is a term that will be used throughout the
labs.

To view the names of the variables, type the command

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(cdc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "genhlth"  "exerany"  "hlthplan" "smoke100" "height"   "weight"  
## [7] "wtdesire" "age"      "gender"
\end{verbatim}

This returns the names \texttt{genhlth}, \texttt{exerany},
\texttt{hlthplan}, \texttt{smoke100}, \texttt{height}, \texttt{weight},
\texttt{wtdesire}, \texttt{age}, and \texttt{gender}. Each one of these
variables corresponds to a question that was asked in the survey. For
example, for \texttt{genhlth}, respondents were asked to evaluate their
general health, responding either excellent, very good, good, fair or
poor. The \texttt{exerany} variable indicates whether the respondent
exercised in the past month (1) or did not (0). Likewise,
\texttt{hlthplan} indicates whether the respondent had some form of
health coverage (1) or did not (0). The \texttt{smoke100} variable
indicates whether the respondent had smoked at least 100 cigarettes in
her lifetime. The other variables record the respondent's
\texttt{height} in inches, \texttt{weight} in pounds as well as their
desired weight, \texttt{wtdesire}, \texttt{age} in years, and
\texttt{gender}.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  How many cases are there in this data set? How many variables? For
  each variable, identify its data type (e.g.~categorical, discrete).
  20000 Cases, 9 Variables Categorical \{distinct groups\}:
  \texttt{genhlth}, \texttt{gender} Discrete
  \{numerical\}:\texttt{exerany}, \texttt{hlthplan}, \texttt{smoke100}
  Continous \{can be infinite\}: \texttt{height}, \texttt{weight},
  \texttt{wtdesire}, \texttt{age}
\end{enumerate}

We can have a look at the first few entries (rows) of our data with the
command

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(cdc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     genhlth exerany hlthplan smoke100 height weight wtdesire age gender
## 1      good       0        1        0     70    175      175  77      m
## 2      good       0        1        1     64    125      115  33      f
## 3      good       1        1        1     60    105      105  49      f
## 4      good       1        1        0     66    132      124  42      f
## 5 very good       0        1        0     61    150      130  55      f
## 6 very good       1        1        0     64    114      114  55      f
\end{verbatim}

and similarly we can look at the last few by typing

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{tail}\NormalTok{(cdc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         genhlth exerany hlthplan smoke100 height weight wtdesire age
## 19995      good       0        1        1     69    224      224  73
## 19996      good       1        1        0     66    215      140  23
## 19997 excellent       0        1        0     73    200      185  35
## 19998      poor       0        1        0     65    216      150  57
## 19999      good       1        1        0     67    165      165  81
## 20000      good       1        1        1     69    170      165  83
##       gender
## 19995      m
## 19996      f
## 19997      m
## 19998      f
## 19999      f
## 20000      m
\end{verbatim}

You could also look at \emph{all} of the data frame at once by typing
its name into the console, but that might be unwise here. We know
\texttt{cdc} has 20,000 rows, so viewing the entire data set would mean
flooding your screen. It's better to take small peeks at the data with
\texttt{head}, \texttt{tail} or the subsetting techniques that you'll
learn in a moment.

\subsection{Summaries and tables}\label{summaries-and-tables}

The BRFSS questionnaire is a massive trove of information. A good first
step in any analysis is to distill all of that information into a few
summary statistics and graphics. As a simple example, the function
\texttt{summary} returns a numerical summary: minimum, first quartile,
median, mean, second quartile, and maximum. For \texttt{weight} this is

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    68.0   140.0   165.0   169.7   190.0   500.0
\end{verbatim}

R also functions like a very fancy calculator. If you wanted to compute
the interquartile range for the respondents' weight, you would look at
the output from the summary command above and then enter

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{190} \OperatorTok{-}\StringTok{ }\DecValTok{140}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 50
\end{verbatim}

R also has built-in functions to compute summary statistics one by one.
For instance, to calculate the mean, median, and variance of
\texttt{weight}, type

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 169.683
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{var}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1606.484
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{median}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 165
\end{verbatim}

While it makes sense to describe a quantitative variable like
\texttt{weight} in terms of these statistics, what about categorical
data? We would instead consider the sample frequency or relative
frequency distribution. The function \texttt{table} does this for you by
counting the number of times each kind of response was given. For
example, to see the number of people who have smoked 100 cigarettes in
their lifetime, type

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{smoke100)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##     0     1 
## 10559  9441
\end{verbatim}

or instead look at the relative frequency distribution by typing

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{smoke100)}\OperatorTok{/}\DecValTok{20000}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##       0       1 
## 0.52795 0.47205
\end{verbatim}

Notice how R automatically divides all entries in the table by 20,000 in
the command above. This is similar to something we observed in the
Introduction to R; when we multiplied or divided a vector with a number,
R applied that action across entries in the vectors. As we see above,
this also works for tables. Next, we make a bar plot of the entries in
the table by putting the table inside the \texttt{barplot} command.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{barplot}\NormalTok{(}\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{smoke100))}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/table-smoke-barplot-1.pdf}

Notice what we've done here! We've computed the table of
\texttt{cdc\$smoke100} and then immediately applied the graphical
function, \texttt{barplot}. This is an important idea: R commands can be
nested. You could also break this into two steps by typing the
following:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{smoke <-}\StringTok{ }\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{smoke100)}

\KeywordTok{barplot}\NormalTok{(smoke)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/table-smoke-barplot-twosteps-1.pdf}

Here, we've made a new object, a table, called \texttt{smoke} (the
contents of which we can see by typing \texttt{smoke} into the console)
and then used it in as the input for \texttt{barplot}. The special
symbol \texttt{\textless{}-} performs an \emph{assignment}, taking the
output of one line of code and saving it into an object in your
workspace. This is another important idea that we'll return to later.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Create a numerical summary for \texttt{height} and \texttt{age}, and
  compute the interquartile range for each.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{height)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   48.00   64.00   67.00   67.18   70.00   93.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#3rd Q - 1st}
\DecValTok{70}\OperatorTok{-}\DecValTok{64}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.00   31.00   43.00   45.07   57.00   99.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{57}\OperatorTok{-}\DecValTok{31}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 26
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  cont'd Compute the relative frequency distribution for \texttt{gender}
  and \texttt{exerany}.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rows <-}\StringTok{ }\DecValTok{20000}
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     m     f 
##  9569 10431
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{exerany)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.0000  1.0000  0.7457  1.0000  1.0000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{genderTable <-}\StringTok{ }\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender)}
\NormalTok{genderTable}\OperatorTok{/}\NormalTok{rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##       m       f 
## 0.47845 0.52155
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{exeranyTable <-}\StringTok{ }\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{exerany}\OperatorTok{/}\NormalTok{rows)}
\NormalTok{exeranyTable}\OperatorTok{/}\NormalTok{rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      0  5e-05 
## 0.2543 0.7457
\end{verbatim}

How many males are in the sample?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender)[}\StringTok{'m'}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    m 
## 9569
\end{verbatim}

What proportion of the sample reports being in excellent health?

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{genhlth)[}\DecValTok{1}\NormalTok{]}\OperatorTok{/}\NormalTok{rows}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## excellent 
##   0.23285
\end{verbatim}

The \texttt{table} command can be used to tabulate any number of
variables that you provide. For example, to examine which participants
have smoked across each gender, we could use the following.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender,cdc}\OperatorTok{$}\NormalTok{smoke100)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
##        0    1
##   m 4547 5022
##   f 6012 4419
\end{verbatim}

Here, we see column labels of 0 and 1. Recall that 1 indicates a
respondent has smoked at least 100 cigarettes. The rows refer to gender.
To create a mosaic plot of this table, we would enter the following
command.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mosaicplot}\NormalTok{(}\KeywordTok{table}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender,cdc}\OperatorTok{$}\NormalTok{smoke100))}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/mosaic-smoke-gender-1.pdf}

We could have accomplished this in two steps by saving the table in one
line and applying \texttt{mosaicplot} in the next (see the table/barplot
example above).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  What does the mosaic plot reveal about smoking habits and gender?
  There is a higher chance that Men smoke more than 100 ciggarettes in
  their lifetime, and less than 50 percent for women. P(Man smokes more
  than 100 in a lifetime) = 5022 / (4547 + 5022) P(Woman smokes more
  than 100 in a lifetime) = 4419 / (6012 + 4419)
\end{enumerate}

\subsection{Interlude: How R thinks about
data}\label{interlude-how-r-thinks-about-data}

We mentioned that R stores data in data frames, which you might think of
as a type of spreadsheet. Each row is a different observation (a
different respondent) and each column is a different variable (the first
is \texttt{genhlth}, the second \texttt{exerany} and so on). We can see
the size of the data frame next to the object name in the workspace or
we can type

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(cdc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20000     9
\end{verbatim}

which will return the number of rows and columns. Now, if we want to
access a subset of the full data frame, we can use row-and-column
notation. For example, to see the sixth variable of the 567th
respondent, use the format

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cdc[}\DecValTok{567}\NormalTok{,}\DecValTok{6}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 160
\end{verbatim}

which means we want the element of our data set that is in the 567th row
(meaning the 567th person or observation) and the 6th column (in this
case, weight). We know that \texttt{weight} is the 6th variable because
it is the 6th entry in the list of variable names

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{names}\NormalTok{(cdc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "genhlth"  "exerany"  "hlthplan" "smoke100" "height"   "weight"  
## [7] "wtdesire" "age"      "gender"
\end{verbatim}

To see the weights for the first 10 respondents we can type

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cdc[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,}\DecValTok{6}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 175 125 105 132 150 114 194 170 150 180
\end{verbatim}

In this expression, we have asked just for rows in the range 1 through
10. R uses the \texttt{:} to create a range of values, so 1:10 expands
to 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. You can see this by entering

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\OperatorTok{:}\DecValTok{10}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]  1  2  3  4  5  6  7  8  9 10
\end{verbatim}

Finally, if we want all of the data for the first 10 respondents, type

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cdc[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      genhlth exerany hlthplan smoke100 height weight wtdesire age gender
## 1       good       0        1        0     70    175      175  77      m
## 2       good       0        1        1     64    125      115  33      f
## 3       good       1        1        1     60    105      105  49      f
## 4       good       1        1        0     66    132      124  42      f
## 5  very good       0        1        0     61    150      130  55      f
## 6  very good       1        1        0     64    114      114  55      f
## 7  very good       1        1        0     71    194      185  31      m
## 8  very good       0        1        0     67    170      160  45      m
## 9       good       0        1        1     65    150      130  27      f
## 10      good       1        1        0     70    180      170  44      m
\end{verbatim}

By leaving out an index or a range (we didn't type anything between the
comma and the square bracket), we get all the columns. When starting out
in R, this is a bit counterintuitive. As a rule, we omit the column
number to see all columns in a data frame. Similarly, if we leave out an
index or range for the rows, we would access all the observations, not
just the 567th, or rows 1 through 10. Try the following to see the
weights for all 20,000 respondents fly by on your screen

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(cdc[,}\DecValTok{6}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 175 125 105 132 150 114
\end{verbatim}

Recall that column 6 represents respondents' weight, so the command
above reported all of the weights in the data set. An alternative method
to access the weight data is by referring to the name. Previously, we
typed \texttt{names(cdc)} to see all the variables contained in the cdc
data set. We can use any of the variable names to select items in our
data set.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 175 125 105 132 150 114
\end{verbatim}

The dollar-sign tells R to look in data frame \texttt{cdc} for the
column called \texttt{weight}. Since that's a single vector, we can
subset it with just a single index inside square brackets. We see the
weight for the 567th respondent by typing

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cdc}\OperatorTok{$}\NormalTok{weight[}\DecValTok{567}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 160
\end{verbatim}

Similarly, for just the first 10 respondents

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cdc}\OperatorTok{$}\NormalTok{weight[}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 175 125 105 132 150 114 194 170 150 180
\end{verbatim}

The command above returns the same result as the
\texttt{cdc{[}1:10,6{]}} command. Both row-and-column notation and
dollar-sign notation are widely used, which one you choose to use
depends on your personal preference.

\subsection{A little more on
subsetting}\label{a-little-more-on-subsetting}

It's often useful to extract all individuals (cases) in a data set that
have specific characteristics. We accomplish this through
\emph{conditioning} commands. First, consider expressions like

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{gender }\OperatorTok{==}\StringTok{ "m"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  TRUE FALSE FALSE FALSE FALSE FALSE
\end{verbatim}

or

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{age }\OperatorTok{>}\StringTok{ }\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE TRUE TRUE TRUE TRUE TRUE
\end{verbatim}

These commands produce a series of \texttt{TRUE} and \texttt{FALSE}
values. There is one value for each respondent, where \texttt{TRUE}
indicates that the person was male (via the first command) or older than
30 (second command).

Suppose we want to extract just the data for the men in the sample, or
just for those over 30. We can use the R function \texttt{subset} to do
that for us. For example, the command

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mdata <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(cdc, cdc}\OperatorTok{$}\NormalTok{gender }\OperatorTok{==}\StringTok{ "m"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

will create a new data set called \texttt{mdata} that contains only the
men from the \texttt{cdc} data set. In addition to finding it in your
workspace alongside its dimensions, you can take a peek at the first
several rows as usual

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(mdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      genhlth exerany hlthplan smoke100 height weight wtdesire age gender
## 1       good       0        1        0     70    175      175  77      m
## 7  very good       1        1        0     71    194      185  31      m
## 8  very good       0        1        0     67    170      160  45      m
## 10      good       1        1        0     70    180      170  44      m
## 11 excellent       1        1        1     69    186      175  46      m
## 12      fair       1        1        1     69    168      148  62      m
\end{verbatim}

This new data set contains all the same variables but just under half
the rows. It is also possible to tell R to keep only specific variables,
which is a topic we'll discuss in a future lab. For now, the important
thing is that we can carve up the data based on values of one or more
variables.

As an aside, you can use several of these conditions together with
\texttt{\&} and \texttt{\textbar{}}. The \texttt{\&} is read ``and'' so
that

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m_and_over30 <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(cdc, gender }\OperatorTok{==}\StringTok{ "m"} \OperatorTok{&}\StringTok{ }\NormalTok{age }\OperatorTok{>}\StringTok{ }\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

will give you the data for men over the age of 30. The
\texttt{\textbar{}} character is read ``or'' so that

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m_or_over30 <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(cdc, gender }\OperatorTok{==}\StringTok{ "m"} \OperatorTok{|}\StringTok{ }\NormalTok{age }\OperatorTok{>}\StringTok{ }\DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

will take people who are men or over the age of 30 (why that's an
interesting group is hard to say, but right now the mechanics of this
are the important thing). In principle, you may use as many ``and'' and
``or'' clauses as you like when forming a subset.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Create a new object called \texttt{under23\_and\_smoke} that contains
  all observations of respondents under the age of 23 that have smoked
  100 cigarettes in their lifetime. Write the command you used to create
  the new object as the answer to this exercise.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{under23_and_smoke <-}\StringTok{ }\KeywordTok{subset}\NormalTok{(cdc, smoke100 }\OperatorTok{==}\StringTok{ }\DecValTok{1} \OperatorTok{&}\StringTok{ }\NormalTok{age }\OperatorTok{<}\StringTok{ }\DecValTok{23}\NormalTok{)}
\NormalTok{under23_and_smoke}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         genhlth exerany hlthplan smoke100 height weight wtdesire age
## 13    excellent       1        0        1     66    185      220  21
## 37    very good       1        0        1     70    160      140  18
## 96    excellent       1        1        1     74    175      200  22
## 180        good       1        1        1     64    190      140  20
## 182   very good       1        1        1     62     92       92  21
## 240   very good       1        0        1     64    125      115  22
## 262        fair       0        1        1     71    185      185  20
## 296        fair       1        1        1     72    185      170  19
## 297   excellent       1        0        1     63    105      100  19
## 300        fair       1        1        1     71    185      150  18
## 306   excellent       0        1        1     66    138      138  21
## 325        fair       1        1        1     63    110      110  20
## 355   very good       1        1        1     64    150      135  20
## 370        good       1        0        1     64    200      120  21
## 414   excellent       1        1        1     63    130      130  22
## 416   very good       1        1        1     75    220      220  18
## 421        good       0        1        1     62    160      130  20
## 439        good       1        1        1     62    102      110  19
## 446   excellent       1        1        1     62    130      120  22
## 484        good       1        1        1     67    165      148  22
## 492   very good       1        1        1     76    253      226  19
## 521   very good       1        1        1     63    100      100  20
## 545   excellent       1        0        1     70    175      150  21
## 588   excellent       1        1        1     69    164      135  21
## 628   excellent       1        1        1     72    165      175  21
## 674   excellent       1        1        1     69    175      175  21
## 693   excellent       1        0        1     77    208      200  21
## 698   excellent       1        0        1     67    140      150  22
## 699        good       1        0        1     69    238      170  18
## 733   excellent       1        0        1     74    173      200  22
## 752        good       1        1        1     68    210      180  20
## 817   very good       1        1        1     70    230      200  22
## 882        good       1        1        1     72    160      160  21
## 958        good       0        0        1     71    120      120  19
## 962   excellent       1        1        1     68    165      180  21
## 1039  very good       0        0        1     68    180      165  21
## 1116       fair       1        0        1     66    163      140  18
## 1147       good       0        0        1     63    150      120  22
## 1172  excellent       1        1        1     73    197      230  18
## 1183  very good       0        0        1     72    135      142  18
## 1200       good       1        1        1     68    150      175  22
## 1241       good       1        1        1     70    180      160  21
## 1256       good       1        1        1     62    150      130  18
## 1328  very good       0        0        1     60    110      110  19
## 1339  excellent       0        1        1     64    138      150  22
## 1370       good       1        1        1     73    180      180  19
## 1379  excellent       1        1        1     64    180      150  20
## 1382  excellent       1        1        1     67    160      160  22
## 1401       good       1        0        1     59    163      130  19
## 1413       fair       0        1        1     64    168      140  18
## 1417       good       0        0        1     59    103      103  21
## 1441  very good       1        1        1     67    115      115  18
## 1488       good       1        1        1     65    130      130  22
## 1489  excellent       1        1        1     74    200      190  22
## 1507       fair       1        0        1     62    110      110  21
## 1513  very good       1        0        1     65    160      120  21
## 1555  very good       1        1        1     73    160      175  19
## 1557       good       1        0        1     65    140      133  21
## 1565       good       1        1        1     72    170      210  19
## 1574       good       1        1        1     69    140      160  19
## 1579       good       0        1        1     72    150      165  19
## 1602  very good       0        1        1     61    120      120  19
## 1638  very good       1        1        1     77    236      225  18
## 1670       good       1        1        1     62     98      110  21
## 1713  excellent       1        1        1     72    180      185  22
## 1751       fair       1        1        1     65    130      115  18
## 1762  excellent       1        0        1     71    165      250  21
## 1790       good       1        0        1     74    150      175  21
## 1806  very good       1        1        1     65    140      120  22
## 1841  very good       1        1        1     70    145      145  20
## 1844  very good       0        1        1     66    130      120  20
## 1880       good       1        1        1     74    155      175  22
## 1920  very good       1        1        1     60    130      120  19
## 1946  very good       1        0        1     63    140      135  20
## 2011  excellent       1        0        1     62     90      115  20
## 2019       fair       1        0        1     72    240      200  22
## 2024  very good       1        1        1     73    210      210  20
## 2071       good       1        1        1     64    120      120  20
## 2106       good       1        1        1     66    145      130  20
## 2119  excellent       1        0        1     63    125      120  21
## 2120  excellent       1        0        1     67    185      155  20
## 2124  excellent       1        1        1     72    175      175  21
## 2143       good       0        0        1     65    120      130  19
## 2161       good       0        1        1     72    135      135  19
## 2163  excellent       1        0        1     75    227      227  21
## 2199  excellent       1        1        1     64    135      135  21
## 2206  excellent       1        0        1     63    125      125  20
## 2209       good       1        1        1     69    140      130  20
## 2244       good       0        0        1     66    145      145  19
## 2252  very good       0        1        1     71    145      180  18
## 2256  very good       1        1        1     69    150      150  20
## 2366  very good       1        0        1     70    150      150  20
## 2391  very good       1        1        1     76    205      205  21
## 2404  excellent       1        1        1     67    175      150  20
## 2409  excellent       1        1        1     66    155      155  18
## 2422  excellent       0        1        1     74    165      165  20
## 2461  very good       1        1        1     74    265      230  20
## 2466  very good       1        1        1     72    160      160  20
## 2476       good       1        1        1     76    225      250  21
## 2495  very good       1        1        1     75    210      200  19
## 2505       fair       1        1        1     70    180      180  19
## 2569  excellent       1        1        1     73    175      195  18
## 2634  very good       1        1        1     69    140      160  19
## 2719  very good       1        1        1     74    220      220  20
## 2728  excellent       1        1        1     71    150      160  19
## 2783       good       1        1        1     59    145      145  22
## 2828       good       1        1        1     69    175      200  20
## 2842       fair       0        0        1     70    135      135  21
## 2880  excellent       1        0        1     71    140      140  18
## 2901       poor       1        0        1     68    125      140  20
## 2918       fair       1        0        1     64    200      165  22
## 3007  very good       1        1        1     72    225      225  21
## 3045  very good       1        1        1     67    125      125  22
## 3049  very good       1        0        1     73    200      215  22
## 3052       good       1        0        1     63    157      125  22
## 3083  very good       0        1        1     67    210      209  19
## 3106  excellent       1        1        1     67    124      117  18
## 3123  excellent       1        1        1     60    110      105  22
## 3151       good       1        1        1     62    160      130  22
## 3171       good       1        0        1     62    151      130  19
## 3203       good       1        1        1     68    145      160  22
## 3204  very good       1        1        1     63    102      102  19
## 3209  very good       1        1        1     65    142      135  20
## 3280  very good       1        1        1     64    156      140  21
## 3288  very good       1        0        1     65    135      135  21
## 3390  very good       1        1        1     64    120      115  20
## 3420       good       1        1        1     71    130      150  18
## 3437  very good       1        1        1     63    110      110  20
## 3449       good       0        0        1     60     85      100  21
## 3454  very good       1        1        1     68    156      156  21
## 3468  very good       0        0        1     68    155      170  22
## 3490       good       1        1        1     67    140      130  20
## 3495       fair       1        1        1     65    204      155  21
## 3502  very good       0        0        1     60    161      115  21
## 3511  very good       1        1        1     73    200      200  18
## 3513  very good       1        1        1     67    180      150  22
## 3533  excellent       1        1        1     74    165      180  19
## 3589  very good       1        1        1     71    168      165  22
## 3599       fair       0        1        1     60    110      115  20
## 3619       fair       1        1        1     64    107      115  22
## 3630  very good       1        1        1     70    150      135  19
## 3642       good       1        1        1     69    140      130  21
## 3731       good       1        1        1     63    115      115  20
## 3757       good       1        1        1     70    165      165  21
## 3759  very good       1        1        1     66    220      200  19
## 3785       good       1        1        1     66    120      120  20
## 3862  very good       1        1        1     65    180      140  18
## 3864  excellent       1        1        1     73    215      170  18
## 3891       good       0        0        1     69    180      165  22
## 3931       good       1        1        1     66    135      115  22
## 3954       good       1        1        1     76    215      225  18
## 3963       good       1        1        1     66    180      130  21
## 3969  excellent       1        1        1     71    145      145  22
## 3976       good       1        1        1     67    112      125  18
## 3999  very good       1        1        1     76    175      205  21
## 4020  very good       0        0        1     63    105      115  18
## 4078  very good       1        0        1     71    145      160  21
## 4097       good       1        1        1     70    185      180  22
## 4127  very good       1        1        1     67    152      165  21
## 4166  very good       1        0        1     72    175      175  22
## 4173  excellent       1        1        1     70    160      180  22
## 4188       good       1        1        1     71    150      150  22
## 4198  very good       1        1        1     67    180      125  18
## 4204       fair       0        0        1     72    180      180  20
## 4265  excellent       1        1        1     70    125      125  20
## 4297  excellent       1        1        1     66    128      115  19
## 4304  very good       1        1        1     72    175      175  19
## 4306       good       1        0        1     67    200      130  22
## 4317       good       1        0        1     64    175      120  22
## 4342  very good       1        1        1     67    165      170  21
## 4368       good       0        1        1     67    210      165  22
## 4411       good       0        0        1     66    162      142  19
## 4426  very good       1        1        1     68    160      150  21
## 4452       good       1        1        1     69    225      200  21
## 4488  excellent       1        0        1     71    120      120  19
## 4500  excellent       1        1        1     71    180      180  22
## 4521  very good       1        1        1     69    135      140  19
## 4583  very good       1        1        1     74    170      170  20
## 4601       good       0        1        1     69    176      200  18
## 4623       good       1        1        1     72    180      180  21
## 4718  very good       1        0        1     64    135      127  21
## 4861       good       1        1        1     72    190      175  22
## 4888  very good       1        1        1     71    200      180  21
## 4913       good       1        1        1     67    138      130  22
## 5019       good       0        1        1     69    135      135  21
## 5048  very good       1        1        1     66    125      125  20
## 5066       good       1        1        1     68    150      160  20
## 5086  excellent       1        1        1     69    155      140  21
## 5107  excellent       1        1        1     63    120      120  22
## 5132       good       1        1        1     68    130      140  21
## 5224  excellent       1        1        1     66    135      160  19
## 5324  very good       1        0        1     69    175      150  20
## 5328  very good       1        1        1     70    175      155  19
## 5351  very good       1        1        1     61    112      112  21
## 5357  very good       1        1        1     62    141      120  20
## 5370  very good       1        1        1     65    105      115  19
## 5450       fair       1        1        1     67    122      122  21
## 5478  very good       1        0        1     68    135      135  18
## 5502  very good       1        1        1     68    200      180  22
## 5504  very good       0        1        1     64    120      140  21
## 5525  very good       1        1        1     69    122      130  20
## 5597  excellent       1        0        1     68    180      160  19
## 5612  very good       1        0        1     71    140      160  22
## 5637  excellent       1        1        1     79    190      190  22
## 5715       good       1        1        1     70    160      190  19
## 5829  very good       0        0        1     70    190      180  21
## 5847       poor       1        0        1     70    135      135  20
## 5935       good       1        1        1     71    200      190  20
## 5941  very good       0        1        1     65    130      110  19
## 5948       good       1        1        1     67    125      110  22
## 5967       good       1        1        1     66    120      120  18
## 5971  very good       1        1        1     68    169      141  20
## 5996  very good       1        1        1     70    170      170  19
## 6047       good       1        0        1     67    145      135  19
## 6085  very good       1        0        1     71    150      150  21
## 6090       good       1        0        1     67    110      150  22
## 6143  excellent       1        1        1     64    108      115  22
## 6157       good       0        0        1     60    145      127  19
## 6199       good       1        1        1     66    160      160  21
## 6246  very good       1        1        1     62    138      115  20
## 6281  excellent       1        0        1     72    200      185  22
## 6282       fair       1        0        1     73    130      150  22
## 6308       good       1        1        1     66    140      155  19
## 6348  excellent       0        1        1     62    137      125  21
## 6366       good       0        1        1     65    110      110  20
## 6390  very good       1        0        1     71    170      170  18
## 6391  very good       1        1        1     71    160      165  19
## 6421       good       1        1        1     77    315      315  18
## 6440  excellent       1        1        1     65    130      120  22
## 6441  very good       1        1        1     64    185      140  18
## 6451  very good       1        1        1     71    165      165  21
## 6455       fair       1        1        1     68    145      145  20
## 6475  very good       1        1        1     72    194      190  20
## 6493  very good       1        1        1     72    175      190  22
## 6590       good       1        1        1     64    105      110  22
## 6649  excellent       1        1        1     71    155      155  22
## 6671       good       1        1        1     62    180      180  20
## 6702  very good       1        1        1     69    125      125  18
## 6713       good       0        0        1     67    182      150  21
## 6753  excellent       1        1        1     72    170      170  18
## 6880       good       1        1        1     66    145      185  21
## 7012       good       1        1        1     63    140      120  21
## 7023       good       1        0        1     70    143      132  19
## 7034  very good       0        1        1     72    160      180  22
## 7050  very good       1        0        1     72    219      190  22
## 7052  very good       1        0        1     68    250      200  21
## 7117  very good       1        0        1     68    175      150  21
## 7154  excellent       1        1        1     76    180      180  22
## 7172  very good       1        1        1     72    185      180  18
## 7174       fair       1        1        1     65    135      125  20
## 7198  very good       1        1        1     65    120      120  20
## 7206       good       1        1        1     74    205      235  20
## 7232       good       0        1        1     62    275      150  22
## 7237  very good       1        1        1     73    203      210  21
## 7249       fair       0        1        1     73    163      175  22
## 7262  very good       0        0        1     63    120      120  22
## 7270       fair       1        0        1     70    165      165  18
## 7286       good       1        0        1     64    145      130  20
## 7290       fair       1        1        1     68    147      155  21
## 7293  very good       1        1        1     62    135      125  18
## 7299  very good       1        1        1     62    140      125  21
## 7318  very good       1        1        1     70    196      185  22
## 7339  very good       1        1        1     72    140      140  21
## 7367  very good       1        1        1     64    125      120  20
## 7373       good       0        1        1     71    207      200  20
## 7422       good       1        1        1     63    125      125  18
## 7461  very good       1        0        1     72    160      225  20
## 7462  excellent       0        1        1     67    180      165  22
## 7498       poor       1        0        1     69    210      190  19
## 7511  very good       1        1        1     67    170      150  18
## 7535  very good       1        1        1     66    180      180  18
## 7593  very good       1        1        1     66    140      130  21
## 7656  excellent       1        1        1     72    150      175  18
## 7769       good       0        1        1     64    125      120  21
## 7776       fair       1        1        1     73    230      200  21
## 7830       good       1        1        1     69    153      153  18
## 7861  very good       1        0        1     73    350      220  19
## 7862  very good       1        1        1     73    165      210  21
## 7879       good       1        1        1     69    150      150  21
## 7915  very good       1        1        1     69    130      150  18
## 7944  excellent       1        1        1     65    125      115  21
## 8059       good       1        1        1     66    127      115  22
## 8082  very good       1        1        1     71    190      190  22
## 8212  very good       0        0        1     68    130      130  20
## 8252  excellent       1        0        1     61    126      110  20
## 8257  very good       1        1        1     66    130      115  21
## 8260  very good       1        1        1     71    200      200  22
## 8278       good       1        1        1     66    145      130  19
## 8283  very good       0        1        1     66    145      145  18
## 8286  very good       1        1        1     70    175      165  22
## 8351  very good       1        1        1     71    175      175  20
## 8365       good       1        1        1     65    215      145  19
## 8420       good       1        1        1     66    131      115  18
## 8529       good       1        1        1     71    155      170  18
## 8694  very good       1        1        1     71    210      200  22
## 8695       good       1        1        1     70    230      180  18
## 8700  very good       1        0        1     67    145      130  22
## 8702       good       0        1        1     76    235      200  22
## 8705  very good       1        0        1     71    165      185  20
## 8714  very good       1        1        1     67    134      125  20
## 8781       good       1        0        1     67    180      120  19
## 8792  excellent       1        1        1     78    145      145  22
## 8810  excellent       0        1        1     73    211      211  20
## 8837  very good       1        0        1     69    145      180  18
## 8869  excellent       1        1        1     62    154      130  21
## 8922       good       1        0        1     71    180      140  20
## 8929  very good       0        0        1     66    113      113  19
## 8931  very good       1        0        1     71    163      163  22
## 8935       good       1        1        1     74    150      150  22
## 8937  excellent       1        1        1     74    163      180  18
## 9018  very good       1        1        1     66    170      140  21
## 9107  very good       1        1        1     68    155      150  18
## 9128       good       1        1        1     63    170      140  22
## 9146       good       1        1        1     71    230      215  22
## 9203       good       1        1        1     76    180      180  18
## 9217       fair       1        0        1     61    100      110  19
## 9252       fair       1        1        1     69    170      150  21
## 9308       good       1        0        1     74    160      250  20
## 9359       fair       0        0        1     69    195      190  22
## 9374  very good       1        0        1     65    120      120  21
## 9442  excellent       1        1        1     72    150      160  20
## 9461  excellent       0        1        1     66    125      125  22
## 9512  very good       1        1        1     74    165      175  18
## 9519       good       1        1        1     73    190      195  22
## 9615       fair       1        1        1     61    130      125  21
## 9617  excellent       1        0        1     62    120      105  21
## 9719  very good       1        1        1     67    127      127  22
## 9733  very good       1        1        1     64    120      150  18
## 9829       fair       1        1        1     64    125      110  22
## 9834  excellent       0        0        1     61    140      130  21
## 9859  very good       1        1        1     68    145      135  21
## 9913       poor       1        0        1     67    175      150  19
## 9921       good       0        0        1     62    130      140  22
## 9937  excellent       1        1        1     69    195      175  20
## 9945       good       1        1        1     69    150      190  18
## 9977  very good       1        1        1     62    103      103  18
## 10029      good       1        1        1     70    105      130  18
## 10078      fair       0        1        1     68    230      160  22
## 10139 very good       1        1        1     69    168      150  21
## 10148      good       1        0        1     75    290      240  19
## 10162      good       1        0        1     67    210      200  21
## 10320 very good       1        1        1     69    180      180  21
## 10335 very good       1        1        1     67    155      155  21
## 10398 very good       1        1        1     71    195      175  21
## 10403 very good       1        0        1     70    130      140  22
## 10433      good       0        1        1     63    160      130  20
## 10459      good       1        0        1     70    135      170  20
## 10461 excellent       1        1        1     65    150      185  22
## 10465 very good       0        1        1     66    143      125  18
## 10476      good       0        0        1     64    110      110  22
## 10494      fair       0        0        1     66    142      130  22
## 10520 excellent       0        1        1     63    108      108  21
## 10540 very good       0        1        1     73    135      145  19
## 10549 very good       1        1        1     73    190      200  19
## 10588 very good       1        1        1     66    135      125  21
## 10598 very good       1        0        1     65    150      140  20
## 10604 very good       1        1        1     75    225      220  21
## 10628      good       1        0        1     73    160      180  21
## 10660 very good       1        1        1     72    170      180  18
## 10843      good       0        1        1     64    120      120  20
## 10882 excellent       0        1        1     68    150      140  22
## 10895      good       1        1        1     65    120      125  20
## 10919 excellent       1        1        1     60    110      110  19
## 10948 excellent       1        1        1     60    115      105  18
## 10952 very good       1        1        1     75    280      240  18
## 10999      good       1        0        1     71    160      200  21
## 11063 very good       1        0        1     71    180      180  22
## 11073 very good       0        1        1     64    125      125  21
## 11190 excellent       1        1        1     70    155      155  18
## 11219 very good       1        1        1     62    113      108  20
## 11246      fair       1        1        1     68    210      160  21
## 11259      good       1        1        1     67    145      135  22
## 11284 very good       1        0        1     65    138      125  22
## 11338 very good       0        0        1     67    145      120  19
## 11339      good       1        1        1     66    155      140  19
## 11349 very good       1        0        1     72    170      170  18
## 11357      good       0        1        1     68    160      175  18
## 11365      good       1        1        1     72    175      175  20
## 11413 very good       1        0        1     70    160      150  22
## 11444 excellent       1        1        1     69    145      135  18
## 11451      good       1        0        1     69    145      145  20
## 11494      good       1        0        1     63    115      100  20
## 11580 very good       1        0        1     73    160      160  18
## 11762 very good       0        1        1     67    130      130  20
## 11813      good       1        1        1     68    160      140  18
## 11826 excellent       1        0        1     65    170      140  21
## 11967 very good       1        1        1     65    117      117  18
## 12055 excellent       1        1        1     63    130      120  20
## 12056 very good       1        1        1     67    140      128  22
## 12118 very good       1        1        1     70    162      160  19
## 12140 very good       1        1        1     66    145      120  20
## 12165      good       1        1        1     63    112      100  19
## 12195 very good       1        1        1     66    140      120  19
## 12248      good       1        0        1     60     95      110  20
## 12262      good       0        1        1     64    135      125  22
## 12313      fair       1        1        1     69    145      145  19
## 12341 very good       0        1        1     69    165      130  19
## 12347      good       1        0        1     76    280      250  21
## 12404 very good       1        1        1     72    180      180  20
## 12482 very good       1        1        1     69    200      180  21
## 12523      poor       1        1        1     66    115      115  21
## 12601      poor       1        0        1     67    150      140  18
## 12624 excellent       1        0        1     64    100      110  22
## 12697      good       0        1        1     66    112      125  20
## 12705 very good       0        1        1     61    110       99  18
## 12863      good       0        1        1     76    200      230  18
## 12888      good       1        0        1     74    165      200  18
## 12974      good       1        1        1     70    205      180  22
## 12988      good       1        0        1     64    175      150  20
## 13014 excellent       1        1        1     70    190      175  22
## 13036      good       1        1        1     71    155      155  19
## 13088 very good       1        1        1     67    140      140  20
## 13101 excellent       1        1        1     75    160      180  22
## 13128 very good       1        0        1     74    200      200  22
## 13146 very good       0        0        1     71    160      160  19
## 13163 very good       1        1        1     75    180      180  20
## 13166 very good       1        0        1     73    179      165  21
## 13238      good       1        0        1     67    170      170  18
## 13265 excellent       1        1        1     63    132      115  19
## 13280 very good       1        1        1     75    200      200  22
## 13314      good       1        0        1     75    160      185  21
## 13378 very good       1        1        1     66    180      135  20
## 13419      good       1        1        1     66    200      160  21
## 13468 excellent       1        1        1     70    165      165  19
## 13514      good       0        0        1     70    195      150  22
## 13550      good       1        1        1     68    130      115  18
## 13572      good       1        1        1     63    115      115  20
## 13616 very good       1        1        1     74    155      170  21
## 13664 very good       1        1        1     67    150      150  21
## 13718 very good       0        1        1     66    150      150  20
## 13766      fair       0        0        1     72    218      185  21
## 13803 very good       0        1        1     71    185      155  22
## 13857      good       1        1        1     66    115      125  20
## 13892 very good       1        1        1     72    200      185  19
## 13905 very good       1        0        1     65    145      110  22
## 13911 excellent       1        1        1     64    110      110  20
## 13990      good       1        0        1     73    160      210  22
## 13995      good       1        0        1     71    175      175  22
## 14000      good       1        1        1     65    140      125  20
## 14003 very good       1        1        1     66    133      123  18
## 14026 very good       1        1        1     64    115      115  21
## 14027      good       0        1        1     66    115      115  19
## 14042 very good       1        1        1     73    165      165  21
## 14054 excellent       1        1        1     76    215      215  20
## 14089 very good       1        0        1     70    140      150  21
## 14103 very good       1        0        1     74    160      185  21
## 14115      fair       1        1        1     64    130      118  18
## 14153 very good       1        0        1     71    160      130  19
## 14172 very good       1        1        1     69    145      145  22
## 14190      good       1        1        1     72    180      150  19
## 14211 excellent       1        1        1     64    130      115  22
## 14223 very good       1        1        1     62    118      118  18
## 14250      good       1        1        1     61    100      120  22
## 14252      good       0        0        1     75    140      170  21
## 14281      good       1        1        1     66    117      117  21
## 14283 very good       1        1        1     63    120      110  19
## 14373 excellent       1        1        1     73    160      180  21
## 14392 very good       1        0        1     62    125      110  22
## 14402      good       1        1        1     61    140      115  19
## 14411      good       1        1        1     69    120      120  19
## 14465      fair       1        1        1     66    120      120  21
## 14478      good       1        1        1     71    145      140  19
## 14501 very good       1        0        1     71    170      170  21
## 14535 excellent       1        1        1     73    177      177  21
## 14536 very good       1        1        1     64    112      115  18
## 14550 very good       1        0        1     63    106      110  19
## 14555 excellent       0        1        1     66    130      120  20
## 14597      good       0        1        1     63    155      130  18
## 14646      good       1        1        1     62    140      140  22
## 14665 very good       1        0        1     70    235      210  22
## 14684      fair       1        0        1     64    145      145  22
## 14738 excellent       1        1        1     75    205      205  20
## 14803 excellent       1        1        1     66    170      150  19
## 14816      good       1        0        1     68    170      170  22
## 14851      good       0        1        1     59    105      100  20
## 14874      good       0        0        1     66    230      180  21
## 14922 very good       1        1        1     73    200      180  19
## 14929      good       1        1        1     69    132      127  22
## 14956 excellent       1        0        1     66    120      145  19
## 14977 excellent       0        1        1     63    131      111  19
## 14987      good       1        1        1     67    125      120  18
## 15032 very good       1        1        1     66    142      135  19
## 15064 excellent       1        0        1     66    150      130  19
## 15168 very good       0        1        1     62    180      135  19
## 15194 very good       1        1        1     69    148      148  22
## 15235 excellent       1        0        1     66    145      120  19
## 15247 very good       1        1        1     66    160      145  20
## 15262      good       1        1        1     71    173      170  20
## 15279 very good       0        0        1     66    200      130  20
## 15313      fair       0        1        1     70    180      140  20
## 15342      fair       1        1        1     72    240      180  18
## 15380      good       0        0        1     75    210      210  19
## 15401 very good       1        0        1     66    120      120  19
## 15409      good       1        1        1     61    140      110  21
## 15466      good       1        1        1     63    107      107  21
## 15488 excellent       1        1        1     67    126      126  21
## 15507      good       0        1        1     73    225      200  21
## 15511 excellent       1        0        1     66    135      160  20
## 15619      fair       0        1        1     65    170      135  20
## 15651      good       1        1        1     65    125      115  20
## 15737 very good       1        0        1     67    144      135  20
## 15769      good       1        0        1     61    150      140  20
## 15781 excellent       0        1        1     64    170      130  21
## 15846 excellent       1        1        1     65    122      120  21
## 15857      good       1        1        1     69    175      165  19
## 15882 very good       1        1        1     65    135      135  19
## 15914      good       1        0        1     72    205      170  22
## 16014 very good       1        0        1     65    130      125  22
## 16022 very good       1        0        1     76    175      200  19
## 16082      good       1        1        1     69    200      170  21
## 16118      good       1        1        1     73    210      205  20
## 16198      poor       1        1        1     67    220      185  19
## 16229      good       0        0        1     67    136      110  20
## 16268 very good       0        1        1     73    160      160  21
## 16271      good       0        0        1     69    200      180  19
## 16303 very good       1        1        1     71    160      160  18
## 16313      fair       0        0        1     68    140      160  21
## 16323      good       0        1        1     65    135      125  21
## 16474 very good       1        1        1     63    128      125  21
## 16485 very good       1        1        1     71    150      150  20
## 16489      good       1        0        1     71    185      170  21
## 16521      good       1        1        1     72    160      175  19
## 16536      good       1        1        1     59    107      103  18
## 16544      fair       1        1        1     66    114      114  18
## 16591 very good       1        0        1     70    170      170  22
## 16594 very good       1        1        1     69    140      140  22
## 16634      good       1        1        1     69    173      155  20
## 16643 excellent       1        1        1     69    152      155  22
## 16661 excellent       1        0        1     66    140      125  21
## 16665 very good       1        1        1     72    195      200  21
## 16681 excellent       1        1        1     64    124      124  18
## 16737 very good       1        1        1     74    180      140  21
## 16770      good       1        1        1     62    200      160  21
## 16814 very good       1        0        1     64    120      105  19
## 16827      poor       1        1        1     66    214      244  20
## 16871 very good       0        1        1     68    160      175  21
## 16882 very good       1        0        1     70    170      190  21
## 17012 very good       1        0        1     71    185      180  21
## 17087      good       1        1        1     70    145      150  21
## 17102      good       1        0        1     65    128      128  19
## 17140 very good       1        1        1     64    210      150  20
## 17186 very good       0        1        1     73    190      150  20
## 17188 very good       1        1        1     70    160      200  18
## 17191 very good       0        0        1     70    165      165  18
## 17193 very good       1        0        1     74    185      200  19
## 17210      fair       0        1        1     64    126      115  19
## 17216 excellent       1        1        1     63     98       98  19
## 17233      good       0        0        1     72    185      160  21
## 17238 very good       1        1        1     68    125      125  22
## 17275 very good       1        1        1     68    210      150  20
## 17311      fair       1        1        1     66    180      180  21
## 17321 excellent       1        1        1     67    142      135  22
## 17358 very good       1        1        1     64    100       80  20
## 17393      good       1        0        1     75    250      225  20
## 17400 very good       1        1        1     70    155      155  19
## 17515      good       1        0        1     64    130      120  21
## 17536 excellent       1        1        1     71    180      180  20
## 17565      good       1        0        1     68    180      170  19
## 17578      fair       1        0        1     62    120      120  21
## 17597      good       1        1        1     62    145      125  21
## 17672      good       0        1        1     74    300      200  22
## 17723 very good       1        1        1     64    140      135  22
## 17763 very good       1        1        1     69    152      152  21
## 17794      good       1        1        1     68    200      180  18
## 17842 very good       1        1        1     63    135      110  19
## 17854 excellent       1        1        1     62    107      107  18
## 17885 very good       1        1        1     74    205      175  22
## 17907 very good       0        0        1     59    115      110  20
## 17914      good       1        1        1     73    175      175  21
## 17988      fair       0        0        1     62    150      130  21
## 18049      fair       0        1        1     70    140      140  20
## 18055      good       0        0        1     62    110      110  22
## 18082 very good       1        1        1     64    120      120  22
## 18198      fair       0        1        1     65    216      130  20
## 18217      good       0        1        1     63    120      115  22
## 18228      good       1        0        1     74    175      175  20
## 18311 very good       1        1        1     74    150      150  21
## 18337 excellent       1        0        1     68    127      125  19
## 18356 very good       1        1        1     69    160      140  22
## 18416 very good       1        1        1     67    147      147  19
## 18482 very good       1        0        1     65    125      125  21
## 18495 very good       1        1        1     65    140      130  22
## 18510 very good       1        0        1     69    200      185  21
## 18547      good       1        1        1     71    140      140  19
## 18590      fair       1        1        1     71    180      180  19
## 18626      good       1        1        1     63    112      112  21
## 18727      good       1        1        1     61     98       98  18
## 18818      good       0        0        1     65    250      150  20
## 18868      good       1        1        1     69    135      160  21
## 18871 very good       0        1        1     63    115      115  20
## 18910 very good       1        1        1     63    104      104  18
## 18924      good       1        1        1     70    163      165  21
## 18931 very good       1        1        1     71    190      180  22
## 18936      good       1        0        1     72    180      195  22
## 19107 very good       1        1        1     70    165      180  21
## 19217      good       1        1        1     67    275      175  21
## 19230 excellent       0        0        1     71    225      190  22
## 19326 very good       1        1        1     60     95       95  18
## 19366      good       1        1        1     65    186      135  19
## 19384      good       1        1        1     67    163      130  20
## 19392 very good       1        1        1     67    115      115  19
## 19488 very good       1        1        1     70    215      200  21
## 19500      poor       0        0        1     74    350      220  19
## 19513 very good       1        1        1     68    216      180  18
## 19550 excellent       1        1        1     73    184      196  19
## 19634      fair       1        1        1     64    140      125  20
## 19637      fair       1        0        1     68    165      175  22
## 19658 very good       1        1        1     68    160      160  22
## 19676      good       1        0        1     73    185      220  22
## 19735      good       0        0        1     66    170      175  22
## 19737      fair       1        1        1     67    135      143  19
## 19743 very good       1        1        1     63    120      117  20
## 19751 very good       1        1        1     64    190      135  20
## 19824 very good       1        0        1     73    195      205  21
## 19853      good       1        0        1     71    168      200  21
## 19860      good       1        1        1     72    170      200  18
## 19864      good       0        0        1     61    107      100  19
## 19890      fair       1        0        1     71    195      200  21
## 19903 very good       1        0        1     70    140      140  20
## 19919 excellent       1        0        1     69    150      170  20
##       gender
## 13         m
## 37         f
## 96         m
## 180        f
## 182        f
## 240        f
## 262        m
## 296        m
## 297        m
## 300        m
## 306        f
## 325        f
## 355        f
## 370        f
## 414        f
## 416        m
## 421        f
## 439        f
## 446        f
## 484        m
## 492        m
## 521        f
## 545        f
## 588        f
## 628        m
## 674        m
## 693        m
## 698        m
## 699        f
## 733        m
## 752        m
## 817        m
## 882        m
## 958        f
## 962        m
## 1039       m
## 1116       f
## 1147       f
## 1172       m
## 1183       m
## 1200       m
## 1241       m
## 1256       f
## 1328       f
## 1339       m
## 1370       m
## 1379       f
## 1382       m
## 1401       f
## 1413       f
## 1417       f
## 1441       f
## 1488       f
## 1489       m
## 1507       f
## 1513       f
## 1555       m
## 1557       f
## 1565       m
## 1574       m
## 1579       m
## 1602       f
## 1638       m
## 1670       f
## 1713       m
## 1751       f
## 1762       m
## 1790       m
## 1806       f
## 1841       m
## 1844       f
## 1880       m
## 1920       f
## 1946       m
## 2011       f
## 2019       m
## 2024       m
## 2071       f
## 2106       f
## 2119       f
## 2120       f
## 2124       m
## 2143       f
## 2161       m
## 2163       m
## 2199       f
## 2206       f
## 2209       f
## 2244       m
## 2252       m
## 2256       m
## 2366       m
## 2391       m
## 2404       f
## 2409       m
## 2422       m
## 2461       m
## 2466       m
## 2476       m
## 2495       m
## 2505       m
## 2569       m
## 2634       m
## 2719       m
## 2728       m
## 2783       f
## 2828       m
## 2842       m
## 2880       m
## 2901       f
## 2918       f
## 3007       m
## 3045       f
## 3049       m
## 3052       f
## 3083       m
## 3106       f
## 3123       f
## 3151       f
## 3171       m
## 3203       m
## 3204       f
## 3209       f
## 3280       f
## 3288       m
## 3390       f
## 3420       m
## 3437       f
## 3449       f
## 3454       f
## 3468       f
## 3490       f
## 3495       f
## 3502       f
## 3511       m
## 3513       f
## 3533       m
## 3589       m
## 3599       f
## 3619       f
## 3630       f
## 3642       f
## 3731       f
## 3757       m
## 3759       m
## 3785       f
## 3862       f
## 3864       m
## 3891       m
## 3931       f
## 3954       m
## 3963       f
## 3969       f
## 3976       f
## 3999       m
## 4020       f
## 4078       m
## 4097       m
## 4127       m
## 4166       m
## 4173       m
## 4188       m
## 4198       f
## 4204       m
## 4265       f
## 4297       f
## 4304       m
## 4306       f
## 4317       f
## 4342       m
## 4368       f
## 4411       f
## 4426       f
## 4452       m
## 4488       m
## 4500       m
## 4521       m
## 4583       m
## 4601       m
## 4623       m
## 4718       f
## 4861       m
## 4888       m
## 4913       f
## 5019       m
## 5048       f
## 5066       m
## 5086       f
## 5107       f
## 5132       m
## 5224       m
## 5324       m
## 5328       m
## 5351       f
## 5357       f
## 5370       f
## 5450       f
## 5478       f
## 5502       m
## 5504       m
## 5525       m
## 5597       m
## 5612       m
## 5637       m
## 5715       m
## 5829       m
## 5847       f
## 5935       m
## 5941       f
## 5948       f
## 5967       f
## 5971       f
## 5996       m
## 6047       f
## 6085       m
## 6090       m
## 6143       f
## 6157       f
## 6199       m
## 6246       f
## 6281       m
## 6282       m
## 6308       m
## 6348       f
## 6366       f
## 6390       m
## 6391       m
## 6421       m
## 6440       f
## 6441       f
## 6451       m
## 6455       m
## 6475       m
## 6493       m
## 6590       f
## 6649       m
## 6671       f
## 6702       f
## 6713       m
## 6753       m
## 6880       m
## 7012       f
## 7023       f
## 7034       m
## 7050       m
## 7052       f
## 7117       m
## 7154       m
## 7172       m
## 7174       f
## 7198       f
## 7206       m
## 7232       f
## 7237       m
## 7249       m
## 7262       f
## 7270       m
## 7286       f
## 7290       m
## 7293       f
## 7299       f
## 7318       m
## 7339       m
## 7367       f
## 7373       m
## 7422       f
## 7461       m
## 7462       m
## 7498       m
## 7511       f
## 7535       f
## 7593       f
## 7656       m
## 7769       f
## 7776       m
## 7830       f
## 7861       m
## 7862       m
## 7879       m
## 7915       m
## 7944       f
## 8059       f
## 8082       m
## 8212       f
## 8252       f
## 8257       f
## 8260       m
## 8278       f
## 8283       f
## 8286       f
## 8351       m
## 8365       f
## 8420       f
## 8529       m
## 8694       m
## 8695       f
## 8700       f
## 8702       m
## 8705       m
## 8714       f
## 8781       f
## 8792       m
## 8810       m
## 8837       m
## 8869       f
## 8922       f
## 8929       f
## 8931       m
## 8935       m
## 8937       m
## 9018       f
## 9107       m
## 9128       f
## 9146       m
## 9203       m
## 9217       f
## 9252       f
## 9308       m
## 9359       m
## 9374       f
## 9442       m
## 9461       f
## 9512       m
## 9519       m
## 9615       f
## 9617       f
## 9719       f
## 9733       f
## 9829       f
## 9834       f
## 9859       f
## 9913       f
## 9921       f
## 9937       m
## 9945       m
## 9977       f
## 10029      f
## 10078      f
## 10139      f
## 10148      m
## 10162      m
## 10320      m
## 10335      m
## 10398      m
## 10403      m
## 10433      f
## 10459      m
## 10461      m
## 10465      f
## 10476      f
## 10494      f
## 10520      f
## 10540      m
## 10549      m
## 10588      f
## 10598      f
## 10604      m
## 10628      m
## 10660      m
## 10843      f
## 10882      m
## 10895      f
## 10919      f
## 10948      f
## 10952      m
## 10999      m
## 11063      m
## 11073      f
## 11190      m
## 11219      f
## 11246      f
## 11259      f
## 11284      f
## 11338      f
## 11339      f
## 11349      m
## 11357      m
## 11365      f
## 11413      f
## 11444      f
## 11451      f
## 11494      f
## 11580      m
## 11762      f
## 11813      f
## 11826      f
## 11967      f
## 12055      f
## 12056      f
## 12118      m
## 12140      f
## 12165      f
## 12195      f
## 12248      f
## 12262      f
## 12313      m
## 12341      f
## 12347      m
## 12404      m
## 12482      m
## 12523      f
## 12601      f
## 12624      f
## 12697      f
## 12705      f
## 12863      m
## 12888      m
## 12974      m
## 12988      f
## 13014      m
## 13036      m
## 13088      m
## 13101      m
## 13128      m
## 13146      m
## 13163      m
## 13166      m
## 13238      m
## 13265      f
## 13280      m
## 13314      m
## 13378      f
## 13419      f
## 13468      m
## 13514      f
## 13550      f
## 13572      f
## 13616      m
## 13664      m
## 13718      m
## 13766      f
## 13803      f
## 13857      f
## 13892      m
## 13905      f
## 13911      f
## 13990      m
## 13995      f
## 14000      f
## 14003      f
## 14026      f
## 14027      f
## 14042      m
## 14054      m
## 14089      m
## 14103      m
## 14115      f
## 14153      m
## 14172      m
## 14190      f
## 14211      f
## 14223      f
## 14250      f
## 14252      m
## 14281      f
## 14283      f
## 14373      m
## 14392      f
## 14402      f
## 14411      f
## 14465      f
## 14478      f
## 14501      m
## 14535      m
## 14536      f
## 14550      f
## 14555      f
## 14597      f
## 14646      m
## 14665      m
## 14684      m
## 14738      m
## 14803      f
## 14816      m
## 14851      f
## 14874      m
## 14922      m
## 14929      f
## 14956      m
## 14977      f
## 14987      f
## 15032      f
## 15064      f
## 15168      f
## 15194      m
## 15235      f
## 15247      f
## 15262      m
## 15279      m
## 15313      f
## 15342      f
## 15380      m
## 15401      m
## 15409      f
## 15466      f
## 15488      f
## 15507      m
## 15511      m
## 15619      f
## 15651      f
## 15737      f
## 15769      f
## 15781      f
## 15846      f
## 15857      m
## 15882      f
## 15914      m
## 16014      f
## 16022      m
## 16082      f
## 16118      m
## 16198      m
## 16229      f
## 16268      m
## 16271      m
## 16303      m
## 16313      m
## 16323      m
## 16474      f
## 16485      m
## 16489      m
## 16521      m
## 16536      f
## 16544      f
## 16591      m
## 16594      f
## 16634      f
## 16643      f
## 16661      f
## 16665      m
## 16681      f
## 16737      m
## 16770      f
## 16814      f
## 16827      f
## 16871      m
## 16882      m
## 17012      m
## 17087      m
## 17102      f
## 17140      f
## 17186      f
## 17188      m
## 17191      m
## 17193      m
## 17210      f
## 17216      f
## 17233      m
## 17238      f
## 17275      m
## 17311      m
## 17321      f
## 17358      f
## 17393      m
## 17400      m
## 17515      f
## 17536      m
## 17565      m
## 17578      f
## 17597      f
## 17672      m
## 17723      f
## 17763      m
## 17794      m
## 17842      f
## 17854      f
## 17885      m
## 17907      f
## 17914      m
## 17988      f
## 18049      m
## 18055      f
## 18082      f
## 18198      f
## 18217      f
## 18228      m
## 18311      m
## 18337      f
## 18356      f
## 18416      f
## 18482      f
## 18495      f
## 18510      m
## 18547      m
## 18590      f
## 18626      f
## 18727      f
## 18818      f
## 18868      m
## 18871      f
## 18910      f
## 18924      m
## 18931      m
## 18936      m
## 19107      m
## 19217      f
## 19230      m
## 19326      f
## 19366      f
## 19384      f
## 19392      f
## 19488      m
## 19500      m
## 19513      m
## 19550      m
## 19634      f
## 19637      m
## 19658      m
## 19676      m
## 19735      m
## 19737      f
## 19743      f
## 19751      f
## 19824      m
## 19853      m
## 19860      m
## 19864      f
## 19890      m
## 19903      m
## 19919      m
\end{verbatim}

\subsection{Quantitative data}\label{quantitative-data}

With our subsetting tools in hand, we'll now return to the task of the
day: making basic summaries of the BRFSS questionnaire. We've already
looked at categorical data such as \texttt{smoke} and \texttt{gender} so
now let's turn our attention to quantitative data. Two common ways to
visualize quantitative data are with box plots and histograms. We can
construct a box plot for a single variable with the following command.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{height)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/boxplot-height-1.pdf}

You can compare the locations of the components of the box by examining
the summary statistics.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{height)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   48.00   64.00   67.00   67.18   70.00   93.00
\end{verbatim}

Confirm that the median and upper and lower quartiles reported in the
numerical summary match those in the graph. The purpose of a boxplot is
to provide a thumbnail sketch of a variable for the purpose of comparing
across several categories. So we can, for example, compare the heights
of men and women with

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{height }\OperatorTok{~}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{gender)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/boxplot-height-gender-1.pdf}

The notation here is new. The \texttt{\textasciitilde{}} character can
be read \emph{versus} or \emph{as a function of}. So we're asking R to
give us a box plots of heights where the groups are defined by gender.

Next let's consider a new variable that doesn't show up directly in this
data set: Body Mass Index (BMI)
(\url{http://en.wikipedia.org/wiki/Body_mass_index}). BMI is a weight to
height ratio and can be calculated as:

\[ BMI = \frac{weight~(lb)}{height~(in)^2} * 703 \]

703 is the approximate conversion factor to change units from metric
(meters and kilograms) to imperial (inches and pounds).

The following two lines first make a new object called \texttt{bmi} and
then creates box plots of these values, defining groups by the variable
\texttt{cdc\$genhlth}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bmi <-}\StringTok{ }\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight }\OperatorTok{/}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{height}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{*}\StringTok{ }\DecValTok{703}
\KeywordTok{boxplot}\NormalTok{(bmi }\OperatorTok{~}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{genhlth)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/boxplot-bmi-1.pdf}

Notice that the first line above is just some arithmetic, but it's
applied to all 20,000 numbers in the \texttt{cdc} data set. That is, for
each of the 20,000 participants, we take their weight, divide by their
height-squared and then multiply by 703. The result is 20,000 BMI
values, one for each respondent. This is one reason why we like R: it
lets us perform computations like this using very simple expressions.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  What does this box plot show? Pick another categorical variable from
  the data set and see how it relates to BMI. List the variable you
  chose, why you might think it would have a relationship to BMI, and
  indicate what the figure seems to suggest.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{bmi =}\StringTok{ }\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight}\OperatorTok{/}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{height}\OperatorTok{^}\DecValTok{2}\NormalTok{))}\OperatorTok{*}\DecValTok{703}

\KeywordTok{boxplot}\NormalTok{(bmi }\OperatorTok{~}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{smoke100,}\DataTypeTok{main=}\StringTok{"BMI and Smoking More than a hundred ciggarettes"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"Smoked more than 100 cigarettes"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"BMI"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/smoke100-bmi-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(bmi }\OperatorTok{~}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{gender,}\DataTypeTok{main=}\StringTok{"BMI and Gender"}\NormalTok{,}\DataTypeTok{xlab=}\StringTok{"gender"}\NormalTok{,}\DataTypeTok{ylab=}\StringTok{"BMI"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/smoke100-bmi-2.pdf}

Neither ciggarette smoking nor gender seem to reveal much about BMI's.
In school we were taught that normal is \textasciitilde{}17 for boys and
\textasciitilde{}22 for women. So I thought there was a clear difference
which would show on the box plot. However, it turns out women's BMI's
are lower across all ages (maybe the difference only exists during
adolescence then normalizes over time?) Also, the ciggs were a stretch -
but I had the idea that any indication of smoking might show skewed
results.

Finally, let's make some histograms. We can look at the histogram for
the age of our respondents with the command

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{age)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/hist-age-1.pdf}

Histograms are generally a very good way to see the shape of a single
distribution, but that shape can change depending on how the data is
split between the different bins. You can control the number of bins by
adding an argument to the command. In the next two lines, we first make
a default histogram of \texttt{bmi} and then one with 50 breaks.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(bmi)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/hist-bmi-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(bmi, }\DataTypeTok{breaks =} \DecValTok{50}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/hist-bmi-2.pdf}

Note that you can flip between plots that you've created by clicking the
forward and backward arrows in the lower right region of RStudio, just
above the plots. How do these two histograms compare?

At this point, we've done a good first pass at analyzing the information
in the BRFSS questionnaire. We've found an interesting association
between smoking and gender, and we can say something about the
relationship between people's assessment of their general health and
their own BMI. We've also picked up essential computing tools -- summary
statistics, subsetting, and plots -- that will serve us well throughout
this course.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\subsection{On Your Own}\label{on-your-own}

\begin{itemize}
\tightlist
\item
  Make a scatterplot of weight versus desired weight. Describe the
  relationship between these two variables.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(}\DataTypeTok{x=}\NormalTok{cdc}\OperatorTok{$}\NormalTok{weight, }\DataTypeTok{xlab=}\StringTok{"weight"}\NormalTok{,}\DataTypeTok{y=}\NormalTok{cdc}\OperatorTok{$}\NormalTok{wtdesire,  }\DataTypeTok{ylab=}\StringTok{"desired weight"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/weight-desiredWeight-1.pdf}

\begin{itemize}
\tightlist
\item
  Let's consider a new variable: the difference between desired weight
  (\texttt{wtdesire}) and current weight (\texttt{weight}). Create this
  new variable by subtracting the two columns in the data frame and
  assigning them to a new object called \texttt{wdiff}.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wdiff <-}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{weight }\OperatorTok{-}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{wtdesire}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  What type of data is \texttt{wdiff}? If an observation \texttt{wdiff}
  is 0, what does this mean about the person's weight and desired
  weight. What if \texttt{wdiff} is positive or negative? If they are
  okay with their weight = 0, want to lose (negative), want to
  gain(positive) generic hypothesis: women want to lose, men want to
  gain.
\item
  Describe the distribution of \texttt{wdiff} in terms of its center,
  shape, and spread, including any plots you use. What does this tell us
  about how people feel about their current weight?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(wdiff)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(wdiff)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/unnamed-chunk-1-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(wdiff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -500.00    0.00   10.00   14.59   21.00  300.00
\end{verbatim}

More people wanted to lose weight than gain.

\begin{itemize}
\tightlist
\item
  Using numerical summaries and a side-by-side box plot, determine if
  men tend to view their weight differently than women.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{boxplot}\NormalTok{(wdiff }\OperatorTok{~}\StringTok{ }\NormalTok{cdc}\OperatorTok{$}\NormalTok{gender)}
\end{Highlighting}
\end{Shaded}

\includegraphics{intro_to_data_files/figure-latex/boxplot weight-gender-1.pdf}
It seems as if men, in this sample, are much closer to their desired
weight. Men also have tight groupings both under and over the zero
value, but women only have tight groupings over.

\begin{itemize}
\tightlist
\item
  Now it's time to get creative. Find the mean and standard deviation of
  \texttt{weight} and determine what proportion of the weights are
  within one standard deviation of the mean.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{mean}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 169.683
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sd}\NormalTok{(cdc}\OperatorTok{$}\NormalTok{weight)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 40.08097
\end{verbatim}


\end{document}
