```{r}
url("https://raw.githubusercontent.com/Pieceofthepy/CUNY_DATA_607_Assignments/CUNY_Projects_607/Projects/Project_1/tournamentinfo.txt")
```

# Create CSV with variables Player Name, Player’s State of Orgin, Total Number of Points, Pre-Rating, and Average Pre Chess Rating of Opponents.

```{r}
# Load stringr,
library(stringr)
```

```{r}
# Read Data in
x <- ("https://raw.githubusercontent.com/Pieceofthepy/CUNY_DATA_607_Assignments/CUNY_Projects_607/Projects/Project_1/tournamentinfo.txt")
raw_tournament_data <- read.delim(x, header = FALSE, stringsAsFactors = FALSE)
```

```{r}
# Remove Header
data_sans_header <- raw_tournament_data[0:196,]
head(data_sans_header)
```

```{r}
# Find Player Names
regex_names <- unlist(str_extract_all(data_sans_header, "[[:upper:][:blank:][:upper:], ]{15,}" ))
regex_names <- regex_names[-1]
regex_names[28] <- "SOFIA ADINA STANESCU-BELLU"
```

```{r}
# Find Player States of Orgin
regex_states <- unlist(str_extract_all(data_sans_header, "[:space:]MI[:space:]|[:space:]ON|[:space:]OH" ))
```

```{r}
# Find Total Scores
regex_scores <- unlist(str_extract_all(data_sans_header, "[[:digit:]].[[:digit:]][:blank:][:blank:]" ))
regex_scores <- unlist(str_extract_all(regex_scores,"[:digit:][:punct:][:digit:]"))
```

```{r}
# Find Pre-Tournament Ratings
regex_pre_tournament_rating <- unlist(str_extract_all(data_sans_header, "[[:space:]][[:digit:]][[:digit:]][[:digit:]][[:digit:][P]]?[[:digit:][P]]?[[:digit:]]?[[:digit:]]?"))
regex_pre_tournament_rating <- regex_pre_tournament_rating[-126]
regex_pre_tournament_rating <- regex_pre_tournament_rating[-123]
regex_pre_tournament_rating <- regex_pre_tournament_rating[-120]
regex_pre_tournament_rating <- regex_pre_tournament_rating[-117]
v <- seq(from = 2, to= 128, by = 2)
regex_pre_tournament_rating <- regex_pre_tournament_rating[v]
regex_pre_tournament_rating_sans_P <- unlist(str_extract_all(regex_pre_tournament_rating, "[[:digit:]][[:digit:]][[:digit:]][[:digit:]]?"))
Pre_Tournament_Rating <- as.numeric(regex_pre_tournament_rating_sans_P)
```

```{r}
# Build Initial Data Frame
Queen_Takes_Bishop <- data.frame(Player = regex_names, Player_State = regex_states, Total_Player_Score = regex_scores, Pre_Tournament_Rating)
Queen_Takes_Bishop
```


```{r}
# Find Average Opponent Rating 
v <- seq(from = 5, to= 196, by = 3)
opponent_lines <- data_sans_header[v] 
Average_Opponent_Rating <- NULL

for (i in 1:length(opponent_lines)){
  opponent_lines1 <- unlist(str_extract_all(opponent_lines[i], "[:space:][[:digit:]]?[[:digit:]]" ))
  opponent_lines1 <- opponent_lines1[-1]
  opponent_lines1 <- unlist(str_extract_all(opponent_lines1, "[[:digit:]]?[[:digit:]]" ))
  opponents_line_1_vector <- as.numeric(opponent_lines1) 
  Average_Opponent_Rating[i] <- round(sum(Queen_Takes_Bishop$Pre_Tournament_Rating[opponents_line_1_vector])/length(opponents_line_1_vector))
}
```

```{r}
# Complete Data Frame
if (length(regex_names) == length(regex_states) && length(regex_scores) == length(regex_states)) {
Queen_Takes_Bishop <- data.frame(Player = regex_names, Player_State = regex_states, Total_Player_Score = regex_scores, Pre_Tournament_Rating, Average_Opponent_Rating)
} else {
  print(length(regex_names))
  print(length(regex_states))
  print(length(regex_scores))
  }
Queen_Takes_Bishop
```

```{r}
# Export to CSV
# Note! Will export to directory where R project is stored. Use setwd() to change to desired directory.
write.csv(Queen_Takes_Bishop, file = "Chess_Tournament_Data.csv")
```